version: '3.8'

services:
  tts-api:
    build: .
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount a volume for persistent audio storage
      - ./audio_output:/app/audio_output
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M 